# Generated by Django 3.1.7 on 2022-05-24 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220524_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 14, 40, 57, 751342)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 14, 40, 57, 751342)),
        ),
    ]
