# Generated by Django 3.1.7 on 2022-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220524_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[('Bt', 'Bullet'), ('Fd', 'Food'), ('Tl', 'Travel'), ('St', 'Sport')], default=None, max_length=2),
        ),
    ]
